version: '3'
services:
  nginx:
    image: nginx:1.27.0-alpine
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile